capitalimmobilier## <center>  Model Creat Dataframe VILLES<br/></center>
<a name="TOP"></a>
- dev : nyx
- Fichier CSV :  correspondance-code-insee-code-postal.csv</a>
    
# Description Fichiers : 
Géolocaliations des communes de FRANCE

# Synthese des Actions :
7 lignes absentes !!! saisie manuel dont une impoté pour code postal
  
**<u>MENU</u>** 
- <a href="#Import">P0 : Import CSV</a>
- <a href="#EDA">P1 : Mini EDA</a>
- <a href="#Nan">P2 : Traitement des Nan</a>
- <a href="#TRANSCO">P3 : Filtres et/ou calculs</a>
- <a href="#EXPORT">P4 : EXPORT (/DATA/EXPORT_CSV/final_xxxxxxx.csv)</a>

PREFIXE FICHIER : GEO

Structure :

    dep                         
    nomdep           
    codecommune                
    nomcommune   
    GEO_latitude
    GEO_longitude
    DBL_geo_point_2d
    DBL_coderegion
    DBL_nomregion
    DBL_bug (1 pour les 7 lignes ajoutées à la main)

ATTENTION 
NE PAS GARDER TOUTES LES COLONNES !! 
DBL_ si info importante pour eventuel calcul de % par exmple

In [1]:
import warnings
warnings.filterwarnings("ignore")

import os
import zipfile
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
def creat_df(file) :
    if os.path.exists(file):
        df_from_csv = pd.read_csv(file, encoding='utf-8', delimiter=';',low_memory=False)
        return df_from_csv
    else:
        print('FICHIER NON TROUVE', file)
        return pd.DataFrame()

## <a name="Import"></a>Partie 0 : Import CSV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="#TOP">&uarr;</a>

In [3]:
file_path2="../../ProjetCommun/DATA_SOURCES/Others/correspondance-code-insee-code-postal.csv"

In [4]:
df2 = creat_df(file_path2) 
df2.head(10)

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape,ID Geofla,Code Commune,Code Canton,Code Arrondissement,Code Département,Code Région
0,59416,59190,MORBECQUE,['NORD'],['NORD-PAS-DE-CALAIS'],['Commune simple'],23.0,4455.0,2.7,"50.67689342861573, 2.536216144331492","{""coordinates"": [[[2.501239302134784, 50.63986...",1237,416,30,4,59,31
1,22102,22330,LANGOURLA,"[""COTES-D'ARMOR""]",['BRETAGNE'],['Commune simple'],170.0,2165.0,0.6,"48.284641107667674, -2.415501011324659","{""coordinates"": [[[-2.416298136623701, 48.2530...",10183,102,9,1,22,53
2,31225,31310,GOUTEVERNISSE,['HAUTE-GARONNE'],['MIDI-PYRENEES'],['Commune simple'],264.0,485.0,0.2,"43.214026301449536, 1.173765920286677","{""coordinates"": [[[1.165580460427912, 43.20037...",20555,225,27,1,31,73
3,23025,23220,BONNAT,['CREUSE'],['LIMOUSIN'],['Chef-lieu canton'],355.0,4554.0,1.3,"46.32301933418213, 1.913450631364578","{""coordinates"": [[[1.952331841746855, 46.28624...",3586,25,6,2,23,74
4,38522,38740,VALJOUFFREY,['ISERE'],['RHONE-ALPES'],['Commune simple'],2009.0,12644.0,0.1,"44.88153491127053, 6.07950399615059","{""coordinates"": [[[6.056489736635054, 44.81581...",1082,522,36,1,38,82
5,21249,21170,ESBARRES,"[""COTE-D'OR""]",['BOURGOGNE'],['Commune simple'],182.0,1587.0,0.8,"47.091069454325485, 5.198246639283228","{""coordinates"": [[[5.195897269928138, 47.06444...",8557,249,29,1,21,26
6,62893,62930,WIMEREUX,['PAS-DE-CALAIS'],['NORD-PAS-DE-CALAIS'],['Commune simple'],24.0,826.0,7.4,"50.77924978918239, 1.613432313096119","{""coordinates"": [[[1.607971003315059, 50.74636...",33814,893,65,3,62,31
7,60331,60590,LABOSSE,['OISE'],['PICARDIE'],['Commune simple'],170.0,1428.0,0.5,"49.35407816266846, 1.898320236754994","{""coordinates"": [[[1.909338677971174, 49.33269...",28855,331,10,1,60,22
8,62625,62770,NOYELLES-LES-HUMIERES,['PAS-DE-CALAIS'],['NORD-PAS-DE-CALAIS'],['Commune simple'],105.0,116.0,0.1,"50.37542375047368, 2.1773776418561592","{""coordinates"": [[[2.185043795569806, 50.37099...",28334,625,39,4,62,31
9,34277,34520,SAINT-MAURICE-NAVACELLES,['HERAULT'],['LANGUEDOC-ROUSSILLON'],['Commune simple'],602.0,6894.0,0.2,"43.84487342385136, 3.506265066900079","{""coordinates"": [[[3.5335903798981603, 43.7881...",25821,277,8,2,34,91

In [5]:
df2.shape

(36742, 17)

In [6]:
df2[df2['Code INSEE']=='78575']

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape,ID Geofla,Code Commune,Code Canton,Code Arrondissement,Code Département,Code Région
14060,78575,78470,SAINT-REMY-LES-CHEVREUSE,['YVELINES'],['ILE-DE-FRANCE'],['Commune simple'],121.0,985.0,8.0,"48.70387375796769, 2.078989249560592","{""coordinates"": [[[2.082078805055938, 48.68545...",16358,575,5,2,78,11

In [7]:
df2['dep'] = df2['Code Département']
df2['nomdep'] = df2['Département'].str.strip('[\'\']')  
df2[df2['Code INSEE']=='78575']

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape,ID Geofla,Code Commune,Code Canton,Code Arrondissement,Code Département,Code Région,dep,nomdep
14060,78575,78470,SAINT-REMY-LES-CHEVREUSE,['YVELINES'],['ILE-DE-FRANCE'],['Commune simple'],121.0,985.0,8.0,"48.70387375796769, 2.078989249560592","{""coordinates"": [[[2.082078805055938, 48.68545...",16358,575,5,2,78,11,78,YVELINES

In [8]:
df2['codecommune'] = df2['Code INSEE'].astype(str).str.zfill(5)
df2['nomcommune'] = df2['Commune'] 
df2[df2['Code INSEE']=='78575']

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,...,ID Geofla,Code Commune,Code Canton,Code Arrondissement,Code Département,Code Région,dep,nomdep,codecommune,nomcommune
14060,78575,78470,SAINT-REMY-LES-CHEVREUSE,['YVELINES'],['ILE-DE-FRANCE'],['Commune simple'],121.0,985.0,8.0,"48.70387375796769, 2.078989249560592",...,16358,575,5,2,78,11,78,YVELINES,78575,SAINT-REMY-LES-CHEVREUSE

In [9]:
df2[['GEO_latitude', 'GEO_longitude']] = df2['geo_point_2d'].str.split(', ', expand=True)
df2[df2['Code INSEE']=='78575']

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,...,Code Canton,Code Arrondissement,Code Département,Code Région,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude
14060,78575,78470,SAINT-REMY-LES-CHEVREUSE,['YVELINES'],['ILE-DE-FRANCE'],['Commune simple'],121.0,985.0,8.0,"48.70387375796769, 2.078989249560592",...,5,2,78,11,78,YVELINES,78575,SAINT-REMY-LES-CHEVREUSE,48.70387375796769,2.078989249560592

In [10]:
df2[['GEO_latitude', 'GEO_longitude']] = df2[['GEO_latitude', 'GEO_longitude']].apply(pd.to_numeric)
df2['DBL_geo_point_2d'] = df2['geo_point_2d'] 
df2['DBL_coderegion'] = df2['Code Région'] 
df2['DBL_nomregion'] = df2['Région'].str.strip('[\'\']') 
df2['DBL_codepostale'] = df2['Code Postal'] 
df2[df2['Code INSEE']=='78575']

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,...,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion,DBL_codepostale
14060,78575,78470,SAINT-REMY-LES-CHEVREUSE,['YVELINES'],['ILE-DE-FRANCE'],['Commune simple'],121.0,985.0,8.0,"48.70387375796769, 2.078989249560592",...,78,YVELINES,78575,SAINT-REMY-LES-CHEVREUSE,48.703874,2.078989,"48.70387375796769, 2.078989249560592",11,ILE-DE-FRANCE,78470

## SQL

In [40]:
df4_sql=df2[
    ['codecommune','DBL_codepostale',
     'nomcommune','nomdep','DBL_nomregion',
     'GEO_latitude','GEO_longitude',
     'Altitude Moyenne','Superficie',
     'Code Département','DBL_coderegion']]
df4_sql['codecommune'] = df4_sql['codecommune'].astype(str).str.zfill(5)
df4_sql['key']=df4_sql['codecommune']
df4_sql[df4_sql['codecommune']=='78575']

,codecommune,DBL_codepostale,nomcommune,nomdep,DBL_nomregion,GEO_latitude,GEO_longitude,Altitude Moyenne,Superficie,Code Département,DBL_coderegion,key
14060,78575,78470,SAINT-REMY-LES-CHEVREUSE,YVELINES,ILE-DE-FRANCE,48.703874,2.078989,121.0,985.0,78,11,78575

In [41]:
df4_sql.set_index('key', inplace=True)
df4_sql[df4_sql['codecommune']=='78575']

,codecommune,DBL_codepostale,nomcommune,nomdep,DBL_nomregion,GEO_latitude,GEO_longitude,Altitude Moyenne,Superficie,Code Département,DBL_coderegion
key,,,,,,,,,,,
78575,78575,78470,SAINT-REMY-LES-CHEVREUSE,YVELINES,ILE-DE-FRANCE,48.703874,2.078989,121.0,985.0,78,11

In [42]:
for i,c in enumerate(df4_sql) :
    print (i,c)

0 codecommune
1 DBL_codepostale
2 nomcommune
3 nomdep
4 DBL_nomregion
5 GEO_latitude
6 GEO_longitude
7 Altitude Moyenne
8 Superficie
9 Code Département
10 DBL_coderegion

In [43]:
new_column_names = {
        'DBL_codepostale': 'codepostale',
        'DBL_nomregion': 'nomregion',
        'GEO_latitude': 'latitude',
        'GEO_longitude': 'longitude',
        'Altitude Moyenne': 'altitude',
        'Superficie': 'superficie',
        'Code Département': 'codedepartement',        
        'DBL_coderegion': 'coderegion'}
df4_sql.rename(columns=new_column_names, inplace=True)
df4_sql[df4_sql['codecommune']=='78575']

,codecommune,codepostale,nomcommune,nomdep,nomregion,latitude,longitude,altitude,superficie,codedepartement,coderegion
key,,,,,,,,,,,
78575,78575,78470,SAINT-REMY-LES-CHEVREUSE,YVELINES,ILE-DE-FRANCE,48.703874,2.078989,121.0,985.0,78,11

In [44]:
df4_sql = df4_sql.drop(df4_sql.columns[0], axis=1)

In [45]:
df4_sql[df4_sql['codepostale']=='89770']

,codepostale,nomcommune,nomdep,nomregion,latitude,longitude,altitude,superficie,codedepartement,coderegion
key,,,,,,,,,,
89069,89770,CHAILLEY,YONNE,BOURGOGNE,48.090402,3.686199,222.0,1696.0,89,26
89048,89770,BOEURS-EN-OTHE,YONNE,BOURGOGNE,48.139871,3.706328,234.0,2232.0,89,26

In [46]:
from sqlalchemy import create_engine, Column, Integer, String, MetaData, Table, update, select
db_path = '../DATA/HistoPlotik.db'
engine = create_engine(f'sqlite:///{db_path}')
metadata = MetaData()

tbl_db_names = metadata.tables.keys()
tbl_db_names

dict_keys([])

In [48]:
# CREATION 
tbl_data = 'villes_tbl'
if tbl_data not in tbl_db_names :
    # Convert DataFrame to a SQL table, using the index as the ID column
    df4_sql.to_sql(tbl_data , con=engine, index=True, if_exists='replace')
    metadata.reflect(bind=engine)
tbl_db_names = metadata.tables.keys()
tbl_db_names

dict_keys(['LGB_reg200_importance_tbl', 'LGB_reg200_resultats_tbl', 'XGBoost_reg200_importance_tbl', 'XGBoost_reg200_resultats_tbl', 'X_col_titr', 'data_tbl', 'villes_tbl', 'y_resultats200_tbl'])

## TEST SQL

In [63]:
import sqlite3

In [67]:
connection = sqlite3.connect(db_path)

# Create a cursor object to execute SQL queries
cursor = connection.cursor()

# Define the SQL query for the join
sql_query = """
SELECT 
    V.*
FROM 
    villes_tbl V
WHERE 
    V.key = '89070'
    OR V.codepostale LIKE 'xx0%'
    OR V.nomcommune LIKE 'XXINT-REM%'
LIMIT 100;
"""

# Execute the SQL query and fetch the result into a DataFrame
test_df = pd.read_sql_query(sql_query, connection)

# Display the result DataFrame
test_df.head(25)

,key,codepostale,nomcommune,nomdep,nomregion,latitude,longitude,altitude,superficie,codedepartement,coderegion
0,89070,89120,CHAMBEUGLE,YONNE,BOURGOGNE,47.858072,3.049252,181.0,714.0,89,26