In [1]:
import pandas as pd

/tmp/ipykernel_2470/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_csv('diplomescommunes.csv')
df.shape

/tmp/ipykernel_2470/3705305927.py:1: DtypeWarning: Columns (0,2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('diplomescommunes.csv')

(37985, 1163)

In [3]:
df.columns

Index(['dep', 'nomdep', 'codecommune', 'nomcommune', 'nodiph1962', 'bach1962',
       'suph1962', 'nodipf1962', 'bacf1962', 'supf1962',
       ...
       'perbac1955', 'persup1955', 'perbac1956', 'persup1956', 'perbac1957',
       'persup1957', 'perbac1958', 'persup1958', 'perbac1959', 'persup1959'],
      dtype='object', length=1163)

In [11]:
df.isna().sum()

dep              0
nomdep         243
codecommune      0
nomcommune       0
nodiph1962     257
              ...
persup1957       0
perbac1958       0
persup1958       0
perbac1959       0
persup1959       0
Length: 1163, dtype: int64

In [5]:
df.duplicated().sum()

0

In [6]:
df.head()

,dep,nomdep,codecommune,nomcommune,nodiph1962,bach1962,suph1962,nodipf1962,bacf1962,supf1962,...,perbac1955,persup1955,perbac1956,persup1956,perbac1957,persup1957,perbac1958,persup1958,perbac1959,persup1959
0,1,AIN,1001,ABERGEMENT-CLEMENCIAT,121.0,4.0,0.0,116.0,0.0,2.0,...,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736
1,1,AIN,1002,ABERGEMENT-DE-VAREY,40.0,0.0,2.0,19.0,0.0,0.0,...,0.263809,0.642062,0.263809,0.642062,0.263809,0.642062,0.263809,0.642062,0.263809,0.642062
2,1,AIN,1003,AMAREINS,32.0,0.0,0.0,35.0,0.0,0.0,...,0.047666,0.092142,0.047666,0.092142,0.047666,0.092142,0.047666,0.092142,0.047666,0.092142
3,1,AIN,1004,AMBERIEU-EN-BUGEY,2241.0,89.0,40.0,2430.0,57.0,16.0,...,0.475746,0.405178,0.475746,0.405178,0.475746,0.405178,0.475746,0.405178,0.475746,0.405178
4,1,AIN,1005,AMBERIEUX-EN-DOMBES,181.0,0.0,2.0,163.0,0.0,2.0,...,0.140375,0.416333,0.140375,0.416333,0.140375,0.416333,0.140375,0.416333,0.140375,0.416333

In [7]:
df.describe()

,nodiph1962,bach1962,suph1962,nodipf1962,bacf1962,supf1962,nodiph1968,bach1968,suph1968,nodipf1968,...,perbac1955,persup1955,perbac1956,persup1956,perbac1957,persup1957,perbac1958,persup1958,perbac1959,persup1959
count,37728.000000,37728.000000,37728.000000,37728.000000,37728.000000,37728.000000,37728.000000,37728.000000,37728.000000,37728.000000,...,3.798500e+04,37985.000000,3.798500e+04,37985.000000,3.798500e+04,37985.000000,3.798500e+04,37985.000000,3.798500e+04,37985.000000
mean,326.638968,10.516036,10.792886,372.345155,10.641036,3.851622,325.345632,20.932782,19.602417,384.291349,...,2.241942e-01,0.212408,2.241942e-01,0.212408,2.241942e-01,0.212408,2.241942e-01,0.212408,2.241942e-01,0.212408
std,2095.527632,98.368516,144.876777,2627.753248,114.148091,57.475133,2086.649182,195.408698,261.948272,2712.483507,...,2.323304e-01,0.222553,2.323304e-01,0.222553,2.323304e-01,0.222553,2.323304e-01,0.222553,2.323304e-01,0.222553
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.353539e-07,0.000004,7.353539e-07,0.000004,7.353539e-07,0.000004,7.353539e-07,0.000004,7.353539e-07,0.000004
25%,48.000000,0.000000,0.000000,50.000000,0.000000,0.000000,48.000000,0.000000,0.000000,52.000000,...,4.307828e-02,0.064249,4.307828e-02,0.064249,4.307828e-02,0.064249,4.307828e-02,0.064249,4.307828e-02,0.064249
50%,96.000000,2.000000,0.000000,97.000000,0.000000,0.000000,96.000000,4.000000,0.000000,100.000000,...,1.449351e-01,0.127707,1.449351e-01,0.127707,1.449351e-01,0.127707,1.449351e-01,0.127707,1.449351e-01,0.127707
75%,197.000000,4.000000,2.000000,209.000000,2.000000,0.000000,196.000000,8.000000,4.000000,216.000000,...,3.310293e-01,0.286870,3.310293e-01,0.286870,3.310293e-01,0.286870,3.310293e-01,0.286870,3.310293e-01,0.286870
max,220015.000000,8447.000000,11937.000000,263314.000000,9317.000000,4446.000000,219084.000000,16780.000000,21584.000000,271804.000000,...,1.000001e+00,0.999996,1.000001e+00,0.999996,1.000001e+00,0.999996,1.000001e+00,0.999996,1.000001e+00,0.999996

In [8]:
col_2017 = []
for c in df.columns:
  if '2017' in c:
    col_2017.append(c) 

print(col_2017)

['nodiph2017', 'bach2017', 'suph2017', 'nodipf2017', 'bacf2017', 'supf2017', 'nodip2017', 'bac2017', 'sup2017', 'pbac2017', 'perbac2017', 'psup2017', 'persup2017']

In [9]:
for c in col_2017:
    print(c, ':', df[c].isna().sum())

nodiph2017 : 0
bach2017 : 0
suph2017 : 0
nodipf2017 : 0
bacf2017 : 0
supf2017 : 0
nodip2017 : 0
bac2017 : 0
sup2017 : 0
pbac2017 : 2755
perbac2017 : 0
psup2017 : 2755
persup2017 : 0