## <center>  Model Creat Dataframe VILLES<br/></center>
<a name="TOP"></a>
- dev : nyx
- Fichier CSV :  correspondance-code-insee-code-postal.csv</a>
    
# Description Fichiers : 
Géolocaliations des communes de FRANCE

# Synthese des Actions :
7 lignes absentes !!! saisie manuel dont une impoté pour code postal
  
**<u>MENU</u>** 
- <a href="#Import">P0 : Import CSV</a>
- <a href="#EDA">P1 : Mini EDA</a>
- <a href="#Nan">P2 : Traitement des Nan</a>
- <a href="#TRANSCO">P3 : Filtres et/ou calculs</a>
- <a href="#EXPORT">P4 : EXPORT (/DATA/EXPORT_CSV/final_xxxxxxx.csv)</a>

PREFIXE FICHIER : GEO

Structure :

    dep                         
    nomdep           
    codecommune                
    nomcommune   
    GEO_latitude
    GEO_longitude
    DBL_geo_point_2d
    DBL_coderegion
    DBL_nomregion
    DBL_bug (1 pour les 7 lignes ajoutées à la main)

ATTENTION 
NE PAS GARDER TOUTES LES COLONNES !! 
DBL_ si info importante pour eventuel calcul de % par exmple

In [182]:
import warnings
warnings.filterwarnings("ignore")

import os
import zipfile
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

In [183]:
def creat_df(file) :
    if os.path.exists(file):
        df_from_csv = pd.read_csv(file, encoding='utf-8', delimiter=';',low_memory=False)
        return df_from_csv
    else:
        print('FICHIER NON TROUVE', file)
        return pd.DataFrame()

## <a name="Import"></a>Partie 0 : Import CSV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="#TOP">&uarr;</a>

In [184]:
file_path2="../../ProjetCommun/DATA_SOURCES/Others/correspondance-code-insee-code-postal.csv"

In [185]:
df2 = creat_df(file_path2) 
df2.head(10)

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape,ID Geofla,Code Commune,Code Canton,Code Arrondissement,Code Département,Code Région
0,59416,59190,MORBECQUE,['NORD'],['NORD-PAS-DE-CALAIS'],['Commune simple'],23.0,4455.0,2.7,"50.67689342861573, 2.536216144331492","{""coordinates"": [[[2.501239302134784, 50.63986...",1237,416,30,4,59,31
1,22102,22330,LANGOURLA,"[""COTES-D'ARMOR""]",['BRETAGNE'],['Commune simple'],170.0,2165.0,0.6,"48.284641107667674, -2.415501011324659","{""coordinates"": [[[-2.416298136623701, 48.2530...",10183,102,9,1,22,53
2,31225,31310,GOUTEVERNISSE,['HAUTE-GARONNE'],['MIDI-PYRENEES'],['Commune simple'],264.0,485.0,0.2,"43.214026301449536, 1.173765920286677","{""coordinates"": [[[1.165580460427912, 43.20037...",20555,225,27,1,31,73
3,23025,23220,BONNAT,['CREUSE'],['LIMOUSIN'],['Chef-lieu canton'],355.0,4554.0,1.3,"46.32301933418213, 1.913450631364578","{""coordinates"": [[[1.952331841746855, 46.28624...",3586,25,6,2,23,74
4,38522,38740,VALJOUFFREY,['ISERE'],['RHONE-ALPES'],['Commune simple'],2009.0,12644.0,0.1,"44.88153491127053, 6.07950399615059","{""coordinates"": [[[6.056489736635054, 44.81581...",1082,522,36,1,38,82
5,21249,21170,ESBARRES,"[""COTE-D'OR""]",['BOURGOGNE'],['Commune simple'],182.0,1587.0,0.8,"47.091069454325485, 5.198246639283228","{""coordinates"": [[[5.195897269928138, 47.06444...",8557,249,29,1,21,26
6,62893,62930,WIMEREUX,['PAS-DE-CALAIS'],['NORD-PAS-DE-CALAIS'],['Commune simple'],24.0,826.0,7.4,"50.77924978918239, 1.613432313096119","{""coordinates"": [[[1.607971003315059, 50.74636...",33814,893,65,3,62,31
7,60331,60590,LABOSSE,['OISE'],['PICARDIE'],['Commune simple'],170.0,1428.0,0.5,"49.35407816266846, 1.898320236754994","{""coordinates"": [[[1.909338677971174, 49.33269...",28855,331,10,1,60,22
8,62625,62770,NOYELLES-LES-HUMIERES,['PAS-DE-CALAIS'],['NORD-PAS-DE-CALAIS'],['Commune simple'],105.0,116.0,0.1,"50.37542375047368, 2.1773776418561592","{""coordinates"": [[[2.185043795569806, 50.37099...",28334,625,39,4,62,31
9,34277,34520,SAINT-MAURICE-NAVACELLES,['HERAULT'],['LANGUEDOC-ROUSSILLON'],['Commune simple'],602.0,6894.0,0.2,"43.84487342385136, 3.506265066900079","{""coordinates"": [[[3.5335903798981603, 43.7881...",25821,277,8,2,34,91

In [186]:
df2.shape

(36742, 17)

In [187]:
df2[df2['Code INSEE']=='78575']

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape,ID Geofla,Code Commune,Code Canton,Code Arrondissement,Code Département,Code Région
14060,78575,78470,SAINT-REMY-LES-CHEVREUSE,['YVELINES'],['ILE-DE-FRANCE'],['Commune simple'],121.0,985.0,8.0,"48.70387375796769, 2.078989249560592","{""coordinates"": [[[2.082078805055938, 48.68545...",16358,575,5,2,78,11

In [188]:
df2['dep'] = df2['Code Département']
df2['nomdep'] = df2['Département'].str.strip('[\'\']')  
df2[df2['Code INSEE']=='78575']

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape,ID Geofla,Code Commune,Code Canton,Code Arrondissement,Code Département,Code Région,dep,nomdep
14060,78575,78470,SAINT-REMY-LES-CHEVREUSE,['YVELINES'],['ILE-DE-FRANCE'],['Commune simple'],121.0,985.0,8.0,"48.70387375796769, 2.078989249560592","{""coordinates"": [[[2.082078805055938, 48.68545...",16358,575,5,2,78,11,78,YVELINES

In [189]:
df2['codecommune'] = df2['Code INSEE'].astype(str).str.zfill(5)
df2['nomcommune'] = df2['Commune'] 
df2[df2['Code INSEE']=='78575']

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,...,ID Geofla,Code Commune,Code Canton,Code Arrondissement,Code Département,Code Région,dep,nomdep,codecommune,nomcommune
14060,78575,78470,SAINT-REMY-LES-CHEVREUSE,['YVELINES'],['ILE-DE-FRANCE'],['Commune simple'],121.0,985.0,8.0,"48.70387375796769, 2.078989249560592",...,16358,575,5,2,78,11,78,YVELINES,78575,SAINT-REMY-LES-CHEVREUSE

In [190]:
df2[['GEO_latitude', 'GEO_longitude']] = df2['geo_point_2d'].str.split(', ', expand=True)
df2[df2['Code INSEE']=='78575']

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,...,Code Canton,Code Arrondissement,Code Département,Code Région,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude
14060,78575,78470,SAINT-REMY-LES-CHEVREUSE,['YVELINES'],['ILE-DE-FRANCE'],['Commune simple'],121.0,985.0,8.0,"48.70387375796769, 2.078989249560592",...,5,2,78,11,78,YVELINES,78575,SAINT-REMY-LES-CHEVREUSE,48.70387375796769,2.078989249560592

In [191]:
df2[['GEO_latitude', 'GEO_longitude']] = df2[['GEO_latitude', 'GEO_longitude']].apply(pd.to_numeric)
df2['DBL_geo_point_2d'] = df2['geo_point_2d'] 
df2['DBL_coderegion'] = df2['Code Région'] 
df2['DBL_nomregion'] = df2['Région'].str.strip('[\'\']') 
df2[df2['Code INSEE']=='78575']

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,...,Code Région,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
14060,78575,78470,SAINT-REMY-LES-CHEVREUSE,['YVELINES'],['ILE-DE-FRANCE'],['Commune simple'],121.0,985.0,8.0,"48.70387375796769, 2.078989249560592",...,11,78,YVELINES,78575,SAINT-REMY-LES-CHEVREUSE,48.703874,2.078989,"48.70387375796769, 2.078989249560592",11,ILE-DE-FRANCE

In [192]:
for i,c in enumerate(df2) :
    print (i,c)

0 Code INSEE
1 Code Postal
2 Commune
3 Département
4 Région
5 Statut
6 Altitude Moyenne
7 Superficie
8 Population
9 geo_point_2d
10 geo_shape
11 ID Geofla
12 Code Commune
13 Code Canton
14 Code Arrondissement
15 Code Département
16 Code Région
17 dep
18 nomdep
19 codecommune
20 nomcommune
21 GEO_latitude
22 GEO_longitude
23 DBL_geo_point_2d
24 DBL_coderegion
25 DBL_nomregion

In [193]:
df2 = df2.drop(df2.columns[:17], axis=1)
df2.head(10)

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
0,59,NORD,59416,MORBECQUE,50.676893,2.536216,"50.67689342861573, 2.536216144331492",31,NORD-PAS-DE-CALAIS
1,22,"""COTES-D'ARMOR""",22102,LANGOURLA,48.284641,-2.415501,"48.284641107667674, -2.415501011324659",53,BRETAGNE
2,31,HAUTE-GARONNE,31225,GOUTEVERNISSE,43.214026,1.173766,"43.214026301449536, 1.173765920286677",73,MIDI-PYRENEES
3,23,CREUSE,23025,BONNAT,46.323019,1.913451,"46.32301933418213, 1.913450631364578",74,LIMOUSIN
4,38,ISERE,38522,VALJOUFFREY,44.881535,6.079504,"44.88153491127053, 6.07950399615059",82,RHONE-ALPES
5,21,"""COTE-D'OR""",21249,ESBARRES,47.091069,5.198247,"47.091069454325485, 5.198246639283228",26,BOURGOGNE
6,62,PAS-DE-CALAIS,62893,WIMEREUX,50.779250,1.613432,"50.77924978918239, 1.613432313096119",31,NORD-PAS-DE-CALAIS
7,60,OISE,60331,LABOSSE,49.354078,1.898320,"49.35407816266846, 1.898320236754994",22,PICARDIE
8,62,PAS-DE-CALAIS,62625,NOYELLES-LES-HUMIERES,50.375424,2.177378,"50.37542375047368, 2.1773776418561592",31,NORD-PAS-DE-CALAIS
9,34,HERAULT,34277,SAINT-MAURICE-NAVACELLES,43.844873,3.506265,"43.84487342385136, 3.506265066900079",91,LANGUEDOC-ROUSSILLON

In [194]:
df2.dtypes

dep                  object
nomdep               object
codecommune          object
nomcommune           object
GEO_latitude        float64
GEO_longitude       float64
DBL_geo_point_2d     object
DBL_coderegion        int64
DBL_nomregion        object
dtype: object

In [195]:
df2['codecommune'] = df2['codecommune'].astype(str).str.zfill(5)
df2.dtypes

dep                  object
nomdep               object
codecommune          object
nomcommune           object
GEO_latitude        float64
GEO_longitude       float64
DBL_geo_point_2d     object
DBL_coderegion        int64
DBL_nomregion        object
dtype: object

In [196]:
df2[df2['codecommune']=='07060']

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
16,07,ARDECHE,07060,CHATEAUNEUF-DE-VERNOUX,44.924924,4.642191,"44.92492404782045, 4.642191100324167",82,RHONE-ALPES

## <a name="EDA"></a>Partie 1 : Mini EDA &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="#TOP">&uarr;</a>

## <a name="Nan"></a>Partie 2 : Traitement des Nan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#TOP">&uarr;</a>

In [197]:
codecommune_listdf2 = df2['codecommune'].tolist()
codecommune_listdf2[1]

'22102'

In [198]:
# Specify the file path
file_path = '../DATA/list_codecommune_leg2022_50inscrits.txt'

# Open the text file and read lines into a list
with open(file_path, 'r', encoding='utf-8') as file:
    lines = [line.strip() for line in file.readlines()]

# Print or manipulate the list of lines as needed
print(lines[0:10], len(lines))

['01001', '01002', '01004', '01005', '01006', '01007', '01008', '01009', '01010', '01011'] 33830

In [199]:
absent = [x for x in lines if x not in codecommune_listdf2]

In [200]:
len(absent)

7

In [201]:
absent

['13055', '55138', '69123', '69380', '75056', '76095', '76601']

### ['13055', '55138', '69123', '69380', '75056', '76095', '76601']

In [204]:
df2[df2['codecommune'] == '13055']

Empty DataFrame
Columns: [dep, nomdep, codecommune, nomcommune, GEO_latitude, GEO_longitude, DBL_geo_point_2d, DBL_coderegion, DBL_nomregion]
Index: []

In [205]:
df2[df2['nomcommune'].str.startswith('MARSEILL')]

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
648,60,OISE,60387,MARSEILLE-EN-BEAUVAISIS,49.575320,1.957650,"49.57531958518338, 1.9576501987936932",22,PICARDIE
1012,18,CHER,18139,MARSEILLES-LES-AUBIGNY,47.070038,2.993932,"47.07003840293559, 2.993931525604912",24,CENTRE
1474,13,BOUCHES-DU-RHONE,13207,MARSEILLE--7E--ARRONDISSEMENT,43.282518,5.363234,"43.28251778002546, 5.363234404349721",93,"""PROVENCE-ALPES-COTE D'AZUR"""
2280,13,BOUCHES-DU-RHONE,13203,MARSEILLE--3E--ARRONDISSEMENT,43.312120,5.380110,"43.31212000462484, 5.380109814230027",93,"""PROVENCE-ALPES-COTE D'AZUR"""
2320,13,BOUCHES-DU-RHONE,13211,MARSEILLE-11E--ARRONDISSEMENT,43.288447,5.483815,"43.288447188052245, 5.483814662290308",93,"""PROVENCE-ALPES-COTE D'AZUR"""
5868,13,BOUCHES-DU-RHONE,13206,MARSEILLE--6E--ARRONDISSEMENT,43.287099,5.381048,"43.28709895455135, 5.381047853938594",93,"""PROVENCE-ALPES-COTE D'AZUR"""
10395,13,BOUCHES-DU-RHONE,13209,MARSEILLE--9E--ARRONDISSEMENT,43.234083,5.452497,"43.23408349271835, 5.452496830665194",93,"""PROVENCE-ALPES-COTE D'AZUR"""
12718,13,BOUCHES-DU-RHONE,13213,MARSEILLE-13E--ARRONDISSEMENT,43.349278,5.433722,"43.34927800054508, 5.433722387381286",93,"""PROVENCE-ALPES-COTE D'AZUR"""
12724,34,HERAULT,34150,MARSEILLAN,43.360578,3.547190,"43.360577600709114, 3.547189637605787",91,LANGUEDOC-ROUSSILLON
16604,13,BOUCHES-DU-RHONE,13212,MARSEILLE-12E--ARRONDISSEMENT,43.307768,5.439916,"43.30776836776201, 5.439915676783301",93,"""PROVENCE-ALPES-COTE D'AZUR"""
19675,13,BOUCHES-DU-RHONE,13216,MARSEILLE-16E--ARRONDISSEMENT,43.364905,5.313378,"43.364905412122766, 5.313378285945362",93,"""PROVENCE-ALPES-COTE D'AZUR"""
23614,13,BOUCHES-DU-RHONE,13205,MARSEILLE--5E--ARRONDISSEMENT,43.292806,5.397577,"43.29280619529811, 5.397577095897295",93,"""PROVENCE-ALPES-COTE D'AZUR"""
24406,13,BOUCHES-DU-RHONE,13210,MARSEILLE-10E--ARRONDISSEMENT,43.275516,5.426811,"43.27551554346898, 5.426811010805492",93,"""PROVENCE-ALPES-COTE D'AZUR"""
24737,13,BOUCHES-DU-RHONE,13208,MARSEILLE--8E--ARRONDISSEMENT,43.241727,5.374644,"43.241727183196915, 5.374644362934933",93,"""PROVENCE-ALPES-COTE D'AZUR"""
29315,13,BOUCHES-DU-RHONE,13214,MARSEILLE-14E--ARRONDISSEMENT,43.345502,5.394089,"43.34550180669167, 5.394089157689507",93,"""PROVENCE-ALPES-COTE D'AZUR"""
29768,13,BOUCHES-DU-RHONE,13202,MARSEILLE--2E--ARRONDISSEMENT,43.312696,5.363650,"43.312696417763945, 5.363649832647911",93,"""PROVENCE-ALPES-COTE D'AZUR"""
30562,65,HAUTES-PYRENEES,65301,MARSEILLAN,43.301413,0.213053,"43.3014129982985, 0.21305255668099202",73,MIDI-PYRENEES
31041,32,GERS,32238,MARSEILLAN,43.488885,0.312582,"43.488884847715354, 0.31258215129433803",73,MIDI-PYRENEES
31320,13,BOUCHES-DU-RHONE,13204,MARSEILLE--4E--ARRONDISSEMENT,43.306733,5.400875,"43.306733355015986, 5.40087488751533",93,"""PROVENCE-ALPES-COTE D'AZUR"""
31432,13,BOUCHES-DU-RHONE,13215,MARSEILLE-15E--ARRONDISSEMENT,43.358795,5.363408,"43.35879475399321, 5.363407896999305",93,"""PROVENCE-ALPES-COTE D'AZUR"""
31526,13,BOUCHES-DU-RHONE,13201,MARSEILLE--1ER-ARRONDISSEMENT,43.299901,5.382279,"43.29990094363678, 5.382278697952185",93,"""PROVENCE-ALPES-COTE D'AZUR"""
36463,11,AUDE,11220,MARSEILLETTE,43.210633,2.548843,"43.210633193537085, 2.548842525678497",91,LANGUEDOC-ROUSSILLON

In [206]:
new_row = df2[df2['codecommune'] == '13201'].copy()

new_row['codecommune'] = '13055'
new_row['nomcommune'] = 'MARSEILLE*'

# Concatenate the original DataFrame with the new row
df2 = pd.concat([df2, new_row], ignore_index=True)

In [207]:
df2[df2['codecommune'] == '13055']

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
36742,13,BOUCHES-DU-RHONE,13055,MARSEILLE*,43.299901,5.382279,"43.29990094363678, 5.382278697952185",93,"""PROVENCE-ALPES-COTE D'AZUR"""

### ['55138', '69123', '69380', '75056', '76095', '76601']

In [208]:
# Culey
df2[df2['nomcommune'].str.startswith('CULEY')]

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
8013,14,CALVADOS,14211,CULEY-LE-PATRY,48.956357,-0.531159,"48.956357101639995, -0.531158873692519",25,BASSE-NORMANDIE

Le code officiel géographique de la commune de Culey est 55138.
Région : Grand Est (44) dont le chef-lieu est la commune de Strasbourg (67482)
Département : Meuse (55) dont le chef-lieu est la commune de Bar-le-Duc (55029)
Arrondissement : Bar-le-Duc (551) dont le chef-lieu est la commune de Bar-le-Duc (55029) 

    01/01/2014 : Culey est rétablie.
    01/01/1973 : Culey est rattachée à Loisey (55298) qui devient Loisey-Culey (fusion simple).

In [209]:
df2[df2['codecommune'] == '55298']

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
11872,55,MEUSE,55298,LOISEY-CULEY,48.767348,5.283225,"48.76734769731965, 5.2832252610511095",41,LORRAINE

In [210]:
new_row = df2[df2['codecommune'] == '55298'].copy()

new_row['codecommune'] = '55138'
new_row['nomcommune'] = 'CULEY*'

# Concatenate the original DataFrame with the new row
df2 = pd.concat([df2, new_row], ignore_index=True)
df2[df2['nomcommune'].str.startswith('CULEY')]

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
8013,14,CALVADOS,14211,CULEY-LE-PATRY,48.956357,-0.531159,"48.956357101639995, -0.531158873692519",25,BASSE-NORMANDIE
36743,55,MEUSE,55138,CULEY*,48.767348,5.283225,"48.76734769731965, 5.2832252610511095",41,LORRAINE

### ['69123', '69380', '75056', '76095', '76601']

    Le code officiel géographique de la commune de Lyon est 69123.
    Région : Auvergne-Rhône-Alpes (84) dont le chef-lieu est la commune de Lyon (69123)
    Département : Rhône (69) dont le chef-lieu est la commune de Lyon (69123)
    Arrondissement : Lyon (691) dont le chef-lieu est la commune de Lyon (69123)

In [211]:
df2[df2['nomcommune'].str.startswith('LYON')]

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
3790,69,RHONE,69384,LYON--4E--ARRONDISSEMENT,45.778687,4.823961,"45.77868675808076, 4.823961126890725",82,RHONE-ALPES
4840,27,EURE,27377,LYONS-LA-FORET,49.393697,1.473559,"49.3936970778067, 1.47355856777582",23,HAUTE-NORMANDIE
6551,69,RHONE,69386,LYON--6E--ARRONDISSEMENT,45.772851,4.852079,"45.772850723857935, 4.8520791143730015",82,RHONE-ALPES
11898,69,RHONE,69387,LYON--7E--ARRONDISSEMENT,45.733410,4.837585,"45.733409841520235, 4.837584957030807",82,RHONE-ALPES
15129,69,RHONE,69389,LYON--9E--ARRONDISSEMENT,45.781781,4.808183,"45.781780588731166, 4.808183278224059",82,RHONE-ALPES
18846,69,RHONE,69382,LYON--2E--ARRONDISSEMENT,45.749256,4.826170,"45.74925603938733, 4.82617032549066",82,RHONE-ALPES
19347,69,RHONE,69381,LYON--1ER-ARRONDISSEMENT,45.769928,4.829225,"45.76992843965841, 4.829224649781766",82,RHONE-ALPES
21982,69,RHONE,69388,LYON--8E--ARRONDISSEMENT,45.734203,4.869357,"45.73420346909841, 4.869357223053562",82,RHONE-ALPES
32465,69,RHONE,69383,LYON--3E--ARRONDISSEMENT,45.753355,4.869185,"45.7533552486214, 4.869185220128738",82,RHONE-ALPES
34509,69,RHONE,69385,LYON--5E--ARRONDISSEMENT,45.755832,4.802254,"45.7558317848881, 4.802253694897703",82,RHONE-ALPES

In [212]:
new_row = df2[df2['codecommune'] == '69381'].copy()

new_row['codecommune'] = '69123'
new_row['nomcommune'] = 'LYON*'

# Concatenate the original DataFrame with the new row
df2 = pd.concat([df2, new_row], ignore_index=True)
df2[df2['nomcommune'].str.startswith('LYON*')]

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
36744,69,RHONE,69123,LYON*,45.769928,4.829225,"45.76992843965841, 4.829224649781766",82,RHONE-ALPES

### ['69380', '75056', '76095', '76601']

NON TROUVE CODE POSTAL
Code postal de Marcilly-d'Azergues
69380
Population en 2012
900 Marcillois
Code INSEE
69125

In [213]:
df2[df2['codecommune'] == '69125']

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
30097,69,RHONE,69125,MARCILLY-D'AZERGUES,45.867988,4.730916,"45.867988264542596, 4.730916110175073",82,RHONE-ALPES

In [214]:
new_row = df2[df2['codecommune'] == '69125'].copy()

new_row['codecommune'] = '69380'
new_row['nomcommune'] = 'Non Renseigne*'

# Concatenate the original DataFrame with the new row
df2 = pd.concat([df2, new_row], ignore_index=True)
df2[df2['codecommune'] == '69380']

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
36745,69,RHONE,69380,Non Renseigne*,45.867988,4.730916,"45.867988264542596, 4.730916110175073",82,RHONE-ALPES

### ['75056', '76095', '76601']

In [215]:
df2[df2['nomcommune'].str.startswith('PARIS-')]

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
322,75,PARIS,75110,PARIS-10E-ARRONDISSEMENT,48.876029,2.361113,"48.87602855694339, 2.361112904561707",11,ILE-DE-FRANCE
436,75,PARIS,75116,PARIS-16E-ARRONDISSEMENT,48.860399,2.262100,"48.86039876035177, 2.262099559395783",11,ILE-DE-FRANCE
2433,75,PARIS,75109,PARIS-9E-ARRONDISSEMENT,48.876896,2.337460,"48.87689616237872, 2.337460241388529",11,ILE-DE-FRANCE
3822,75,PARIS,75115,PARIS-15E-ARRONDISSEMENT,48.840155,2.293559,"48.84015541860987, 2.293559372435076",11,ILE-DE-FRANCE
6744,75,PARIS,75102,PARIS-2E-ARRONDISSEMENT,48.867903,2.344107,"48.86790337886785, 2.344107166658533",11,ILE-DE-FRANCE
6819,75,PARIS,75111,PARIS-11E-ARRONDISSEMENT,48.859415,2.378741,"48.85941549762748, 2.378741060237548",11,ILE-DE-FRANCE
9988,71,SAONE-ET-LOIRE,71343,PARIS-L'HOPITAL,46.912789,4.639586,"46.912788557458065, 4.639585731456624",26,BOURGOGNE
13566,75,PARIS,75118,PARIS-18E-ARRONDISSEMENT,48.892735,2.348712,"48.892735074561706, 2.348711933867703",11,ILE-DE-FRANCE
14296,75,PARIS,75105,PARIS-5E-ARRONDISSEMENT,48.844509,2.349859,"48.844508659617546, 2.349859385560182",11,ILE-DE-FRANCE
19937,75,PARIS,75108,PARIS-8E-ARRONDISSEMENT,48.872527,2.312583,"48.87252726662346, 2.312582560420059",11,ILE-DE-FRANCE
20560,75,PARIS,75113,PARIS-13E-ARRONDISSEMENT,48.828718,2.362468,"48.82871768452136, 2.362468228516128",11,ILE-DE-FRANCE
20779,75,PARIS,75112,PARIS-12E-ARRONDISSEMENT,48.835156,2.419807,"48.83515623066034, 2.419807034965275",11,ILE-DE-FRANCE
22557,75,PARIS,75101,PARIS-1ER-ARRONDISSEMENT,48.862630,2.336293,"48.8626304851685, 2.336293446550539",11,ILE-DE-FRANCE
26173,75,PARIS,75117,PARIS-17E-ARRONDISSEMENT,48.887337,2.307486,"48.88733716648682, 2.307485559493426",11,ILE-DE-FRANCE
26467,75,PARIS,75104,PARIS-4E-ARRONDISSEMENT,48.854228,2.357362,"48.854228281954754, 2.357361938142205",11,ILE-DE-FRANCE
29510,75,PARIS,75119,PARIS-19E-ARRONDISSEMENT,48.886869,2.384694,"48.88686862295828, 2.384694327870042",11,ILE-DE-FRANCE
29579,75,PARIS,75120,PARIS-20E-ARRONDISSEMENT,48.863187,2.400820,"48.86318677744551, 2.400819826729021",11,ILE-DE-FRANCE
29853,75,PARIS,75107,PARIS-7E-ARRONDISSEMENT,48.856083,2.312439,"48.85608259819694, 2.312438687733857",11,ILE-DE-FRANCE
33654,75,PARIS,75103,PARIS-3E-ARRONDISSEMENT,48.863054,2.359361,"48.86305413181178, 2.359361058970589",11,ILE-DE-FRANCE
34023,75,PARIS,75106,PARIS-6E-ARRONDISSEMENT,48.848968,2.332671,"48.84896809191946, 2.332670898588416",11,ILE-DE-FRANCE
36683,75,PARIS,75114,PARIS-14E-ARRONDISSEMENT,48.828993,2.327101,"48.82899321160942, 2.327100883257538",11,ILE-DE-FRANCE

In [216]:
# 75101
new_row = df2[df2['codecommune'] == '75101'].copy()

new_row['codecommune'] = '75056'
new_row['nomcommune'] = 'PARIS*'

# Concatenate the original DataFrame with the new row
df2 = pd.concat([df2, new_row], ignore_index=True)
df2[df2['codecommune'] == '75056']

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
36746,75,PARIS,75056,PARIS*,48.86263,2.336293,"48.8626304851685, 2.336293446550539",11,ILE-DE-FRANCE

### ['76095', '76601']
Bihorel


    01/01/2014 : Bihorel est rétablie.
    01/01/2012 : Bihorel devient commune déléguée au sein de Bois-Guillaume-Bihorel (76108) (commune nouvelle).

In [217]:
df2[df2['codecommune'] == '76108']

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
9348,76,SEINE-MARITIME,76108,BOIS-GUILLAUME-BIHOREL,49.471762,1.120226,"49.471761571405764, 1.12022637351156",23,HAUTE-NORMANDIE

In [218]:
new_row = df2[df2['codecommune'] == '76108'].copy()

new_row['codecommune'] = '76095'
new_row['nomcommune'] = 'BIHOREL*'

# Concatenate the original DataFrame with the new row
df2 = pd.concat([df2, new_row], ignore_index=True)
df2[df2['codecommune'] == '76095']

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
36747,76,SEINE-MARITIME,76095,BIHOREL*,49.471762,1.120226,"49.471761571405764, 1.12022637351156",23,HAUTE-NORMANDIE

### ['76601']

Saint-Lucien
Le code officiel géographique de la commune de Saint-Lucien est 76601.
Région : Normandie (28) dont le chef-lieu est la commune de Rouen (76540)
Département : Seine-Maritime (76) dont le chef-lieu est la commune de Rouen (76540)
Arrondissement : Dieppe (761) dont le chef-lieu est la commune de Dieppe (76217) 


    01/01/2017 : Saint-Lucien est rétablie.
    01/06/1973 : Saint-Lucien est rattachée à Sigy-en-Bray (76676) (fusion association).

In [219]:
df2[df2['nomcommune'].str.startswith('SAINT-LUCIEN')]

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
22157,28,EURE-ET-LOIR,28349,SAINT-LUCIEN,48.639163,1.623309,"48.63916266127105, 1.6233092495116521",24,CENTRE

In [220]:
df2[df2['codecommune'] == '76676']

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
5117,76,SEINE-MARITIME,76676,SIGY-EN-BRAY,49.533563,1.466921,"49.53356288523321, 1.4669213469817501",23,HAUTE-NORMANDIE

In [221]:
new_row = df2[df2['codecommune'] == '76676'].copy()

new_row['codecommune'] = '76601'
new_row['nomcommune'] = 'SAINT-LUCIEN*'

# Concatenate the original DataFrame with the new row
df2 = pd.concat([df2, new_row], ignore_index=True)
df2[df2['codecommune'] == '76601']

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
36748,76,SEINE-MARITIME,76601,SAINT-LUCIEN*,49.533563,1.466921,"49.53356288523321, 1.4669213469817501",23,HAUTE-NORMANDIE

In [222]:
codecommune_listdf2_corr = df2['codecommune'].tolist()

In [223]:
absent = [x for x in lines if x not in codecommune_listdf2_corr]

In [224]:
len(absent)

0

In [229]:
df2[df2['nomcommune'].str.endswith('*')]

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion
36742,13,BOUCHES-DU-RHONE,13055,MARSEILLE*,43.299901,5.382279,"43.29990094363678, 5.382278697952185",93,"""PROVENCE-ALPES-COTE D'AZUR"""
36743,55,MEUSE,55138,CULEY*,48.767348,5.283225,"48.76734769731965, 5.2832252610511095",41,LORRAINE
36744,69,RHONE,69123,LYON*,45.769928,4.829225,"45.76992843965841, 4.829224649781766",82,RHONE-ALPES
36745,69,RHONE,69380,Non Renseigne*,45.867988,4.730916,"45.867988264542596, 4.730916110175073",82,RHONE-ALPES
36746,75,PARIS,75056,PARIS*,48.862630,2.336293,"48.8626304851685, 2.336293446550539",11,ILE-DE-FRANCE
36747,76,SEINE-MARITIME,76095,BIHOREL*,49.471762,1.120226,"49.471761571405764, 1.12022637351156",23,HAUTE-NORMANDIE
36748,76,SEINE-MARITIME,76601,SAINT-LUCIEN*,49.533563,1.466921,"49.53356288523321, 1.4669213469817501",23,HAUTE-NORMANDIE

In [230]:
df2['DBL_bug'] = df2['nomcommune'].str.endswith('*').astype(int)
df2.head(5)

,dep,nomdep,codecommune,nomcommune,GEO_latitude,GEO_longitude,DBL_geo_point_2d,DBL_coderegion,DBL_nomregion,DBL_bug
0,59,NORD,59416,MORBECQUE,50.676893,2.536216,"50.67689342861573, 2.536216144331492",31,NORD-PAS-DE-CALAIS,0
1,22,"""COTES-D'ARMOR""",22102,LANGOURLA,48.284641,-2.415501,"48.284641107667674, -2.415501011324659",53,BRETAGNE,0
2,31,HAUTE-GARONNE,31225,GOUTEVERNISSE,43.214026,1.173766,"43.214026301449536, 1.173765920286677",73,MIDI-PYRENEES,0
3,23,CREUSE,23025,BONNAT,46.323019,1.913451,"46.32301933418213, 1.913450631364578",74,LIMOUSIN,0
4,38,ISERE,38522,VALJOUFFREY,44.881535,6.079504,"44.88153491127053, 6.07950399615059",82,RHONE-ALPES,0

## <a name="TRANSCO"></a>Partie 3 : Filtres et/ou calculs&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#TOP">&uarr;</a>

In [231]:
len(lines)

33830

In [232]:
len(df2)

36749

In [233]:
df2_filtered = df2[df2['codecommune'].isin(lines)]
df2_filtered.shape

(33830, 10)

## <a name="EXPORT"></a>Partie 4 : EXPORT&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#TOP">&uarr;</a>
- ../DATA/EXPORT_CSV/
- final
- GEO
- correspondance-code-insee-code-postal.csv

Attention : sources CSV dans Others

In [234]:
path_export='../DATA/EXPORT_CSV/final_GEO_correspondance-code-insee-code-postal.csv'

In [235]:
df2_filtered.to_csv(path_export, sep=';', index=False)

print(f'DataFrame exported to: {path_export}')

DataFrame exported to: ../DATA/EXPORT_CSV/final_GEO_correspondance-code-insee-code-postal.csv