## <center>  Model Creat Dataframe to EXPORT from CSV<br/></center>
<a name="TOP">dev :
    Fichier CSV :  xxxxxxx.csv</a>
    
# Description Fichiers :

# Synthese des Actions :

  
**<u>MENU</u>** 
- <a href="#EDA">P0 : Mini EDA</a>
- <a href="#Import">P1 : Import CSV</a>
- <a href="#Nan">P1 : Traitement des Nan</a>
- <a href="#Nan">P2 : Filtres et calculs</a>
- <a href="#Nan">P3 : EXPORT (/DATA/EXPORT_CSV/final_xxxxxxx.csv)</a>

In [1]:
import pandas as pd
import numpy as np

/tmp/ipykernel_10987/2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

## <a name="EDA"></a>Partie 0 : Mini EDA &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#TOP">&uarr;</a>

dep: Code du département.

nomdep: Nom du département.

nomcommune: Nom de la commune.

nodiph: Nombre total de diplômés hommes

bach: Nombre de bacheliers hommes

suph: Nombre de diplômés de l'enseignement supérieur hommes

nodipf: Nombre total de femmes diplômées.

bacf: Nombre de femmes bachelères.

supf: Nombre de femmes diplômées de l'enseignement supérieur.

perbac : représentent le pourcentage de bacheliers par rapport à la population totale.

persup : représentent le pourcentage de diplômés de l'enseignement supérieur par rapport à la 

population totale.

## <a name="Import"></a>Partie 1 : Import CSV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#TOP">&uarr;</a>

In [2]:
df = pd.read_csv('diplomescommunes.csv', encoding='utf-8')
df.shape

/tmp/ipykernel_10987/3792078603.py:1: DtypeWarning: Columns (0,2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('diplomescommunes.csv', encoding='utf-8')

(37985, 1163)

In [3]:
df.columns

Index(['dep', 'nomdep', 'codecommune', 'nomcommune', 'nodiph1962', 'bach1962',
       'suph1962', 'nodipf1962', 'bacf1962', 'supf1962',
       ...
       'perbac1955', 'persup1955', 'perbac1956', 'persup1956', 'perbac1957',
       'persup1957', 'perbac1958', 'persup1958', 'perbac1959', 'persup1959'],
      dtype='object', length=1163)

In [4]:
colonnes_non_nulles = df.columns[df.notna().all()]

for colonne in colonnes_non_nulles:
    print(colonne)

dep
codecommune
nomcommune
nodiph1960
nodiph1961
nodiph2017
nodiph2018
nodiph2019
nodiph2020
nodiph2021
nodiph2022
bach1960
bach1961
bach2017
bach2018
bach2019
bach2020
bach2021
bach2022
suph1960
suph1961
suph2017
suph2018
suph2019
suph2020
suph2021
suph2022
nodipf1960
nodipf1961
nodipf2017
nodipf2018
nodipf2019
nodipf2020
nodipf2021
nodipf2022
bacf1960
bacf1961
bacf2017
bacf2018
bacf2019
bacf2020
bacf2021
bacf2022
supf1960
supf1961
supf2017
supf2018
supf2019
supf2020
supf2021
supf2022
nodip1960
nodip1961
nodip2017
nodip2018
nodip2019
nodip2020
nodip2021
nodip2022
bac1960
bac1961
bac2017
bac2018
bac2019
bac2020
bac2021
bac2022
sup1960
sup1961
sup2017
sup2018
sup2019
sup2020
sup2021
sup2022
perbac1960
perbac1961
perbac2017
perbac2018
perbac2019
perbac2020
perbac2021
perbac2022
persup1960
persup1961
persup2017
persup2018
persup2019
persup2020
persup2021
persup2022
perbac1790
persup1790
perbac1791
persup1791
perbac1792
persup1792
perbac1793
persup1793
perbac1794
persup1794
perbac1795
persup1795
perbac1796
persup1796
perbac1797
persup1797
perbac1798
persup1798
perbac1799
persup1799
perbac1800
persup1800
perbac1801
persup1801
perbac1802
persup1802
perbac1803
persup1803
perbac1804
persup1804
perbac1805
persup1805
perbac1806
persup1806
perbac1807
persup1807
perbac1808
persup1808
perbac1809
persup1809
perbac1810
persup1810
perbac1811
persup1811
perbac1812
persup1812
perbac1813
persup1813
perbac1814
persup1814
perbac1815
persup1815
perbac1816
persup1816
perbac1817
persup1817
perbac1818
persup1818
perbac1819
persup1819
perbac1820
persup1820
perbac1821
persup1821
perbac1822
persup1822
perbac1823
persup1823
perbac1824
persup1824
perbac1825
persup1825
perbac1826
persup1826
perbac1827
persup1827
perbac1828
persup1828
perbac1829
persup1829
perbac1830
persup1830
perbac1831
persup1831
perbac1832
persup1832
perbac1833
persup1833
perbac1834
persup1834
perbac1835
persup1835
perbac1836
persup1836
perbac1837
persup1837
perbac1838
persup1838
perbac1839
persup1839
perbac1840
persup1840
perbac1841
persup1841
perbac1842
persup1842
perbac1843
persup1843
perbac1844
persup1844
perbac1845
persup1845
perbac1846
persup1846
perbac1847
persup1847
perbac1848
persup1848
perbac1849
persup1849
perbac1850
persup1850
perbac1851
persup1851
perbac1852
persup1852
perbac1853
persup1853
perbac1854
persup1854
perbac1855
persup1855
perbac1856
persup1856
perbac1857
persup1857
perbac1858
persup1858
perbac1859
persup1859
perbac1860
persup1860
perbac1861
persup1861
perbac1862
persup1862
perbac1863
persup1863
perbac1864
persup1864
perbac1865
persup1865
perbac1866
persup1866
perbac1867
persup1867
perbac1868
persup1868
perbac1869
persup1869
perbac1870
persup1870
perbac1871
persup1871
perbac1872
persup1872
perbac1873
persup1873
perbac1874
persup1874
perbac1875
persup1875
perbac1876
persup1876
perbac1877
persup1877
perbac1878
persup1878
perbac1879
persup1879
perbac1880
persup1880
perbac1881
persup1881
perbac1882
persup1882
perbac1883
persup1883
perbac1884
persup1884
perbac1885
persup1885
perbac1886
persup1886
perbac1887
persup1887
perbac1888
persup1888
perbac1889
persup1889
perbac1890
persup1890
perbac1891
persup1891
perbac1892
persup1892
perbac1893
persup1893
perbac1894
persup1894
perbac1895
persup1895
perbac1896
persup1896
perbac1897
persup1897
perbac1898
persup1898
perbac1899
persup1899
perbac1900
persup1900
perbac1901
persup1901
perbac1902
persup1902
perbac1903
persup1903
perbac1904
persup1904
perbac1905
persup1905
perbac1906
persup1906
perbac1907
persup1907
perbac1908
persup1908
perbac1909
persup1909
perbac1910
persup1910
perbac1911
persup1911
perbac1912
persup1912
perbac1913
persup1913
perbac1914
persup1914
perbac1915
persup1915
perbac1916
persup1916
perbac1917
persup1917
perbac1918
persup1918
perbac1919
persup1919
perbac1920
persup1920
perbac1921
persup1921
perbac1922
persup1922
perbac1923
persup1923
perbac1924
persup1924
perbac1925
persup1925
perbac1926
persup1926
perbac1927
persup1927
perbac1928
persup1928
perbac1929
persup1929
perbac1930
persup1930
perbac1931
persup1931
perbac1932
persup1932
perbac1933
persup1933
perbac1934
persup1934
perbac1935
persup1935
perbac1936
persup1936
perbac1937
persup1937
perbac1938
persup1938
perbac1939
persup1939
perbac1940
persup1940
perbac1941
persup1941
perbac1942
persup1942
perbac1943
persup1943
perbac1944
persup1944
perbac1945
persup1945
perbac1946
persup1946
perbac1947
persup1947
perbac1948
persup1948
perbac1949
persup1949
perbac1950
persup1950
perbac1951
persup1951
perbac1952
persup1952
perbac1953
persup1953
perbac1954
persup1954
perbac1955
persup1955
perbac1956
persup1956
perbac1957
persup1957
perbac1958
persup1958
perbac1959
persup1959

In [5]:
df.head()

,dep,nomdep,codecommune,nomcommune,nodiph1962,bach1962,suph1962,nodipf1962,bacf1962,supf1962,...,perbac1955,persup1955,perbac1956,persup1956,perbac1957,persup1957,perbac1958,persup1958,perbac1959,persup1959
0,1,AIN,1001,ABERGEMENT-CLEMENCIAT,121.0,4.0,0.0,116.0,0.0,2.0,...,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736
1,1,AIN,1002,ABERGEMENT-DE-VAREY,40.0,0.0,2.0,19.0,0.0,0.0,...,0.263809,0.642062,0.263809,0.642062,0.263809,0.642062,0.263809,0.642062,0.263809,0.642062
2,1,AIN,1003,AMAREINS,32.0,0.0,0.0,35.0,0.0,0.0,...,0.047666,0.092142,0.047666,0.092142,0.047666,0.092142,0.047666,0.092142,0.047666,0.092142
3,1,AIN,1004,AMBERIEU-EN-BUGEY,2241.0,89.0,40.0,2430.0,57.0,16.0,...,0.475746,0.405178,0.475746,0.405178,0.475746,0.405178,0.475746,0.405178,0.475746,0.405178
4,1,AIN,1005,AMBERIEUX-EN-DOMBES,181.0,0.0,2.0,163.0,0.0,2.0,...,0.140375,0.416333,0.140375,0.416333,0.140375,0.416333,0.140375,0.416333,0.140375,0.416333

## <a name="Import"></a>Partie 2 : Renommer &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#TOP">&uarr;</a>

In [6]:
df['DBL_dep'] = df.dep
df['DBL_nomdep'] = df.nomdep
df['DBL_nomcommune'] = df.nomcommune

In [7]:
df['codecommune'] = df['codecommune'].astype(str).str.zfill(5)

In [8]:
file_path = '../DATA/list_codecommune_leg2022_50inscrits.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    lines = [line.strip() for line in file.readlines()]

print(lines[0:10], len(lines))

['01001', '01002', '01004', '01005', '01006', '01007', '01008', '01009', '01010', '01011'] 33830

In [9]:
codecommune_listdf = df['codecommune'].tolist()

In [10]:
absent = [x for x in lines if x not in codecommune_listdf]
len (absent)

27

In [11]:
df_filtered = df[df['codecommune'].isin(lines)]

In [12]:
df_filtered.shape

(33803, 1166)

In [13]:
col = []
for c in df_filtered.columns:
  if 'bach' in c or 'bacf' in c or 'suph' in c or 'supf' in c:
    col.append(c)

colbis = []
for c in col :
  if '2022' in c or '2012' in c or '2002' in c or '1992' in c or '2017' in c:
    colbis.append(c)

colbis

['bach1992',
 'bach2002',
 'bach2012',
 'bach2017',
 'bach2022',
 'suph1992',
 'suph2002',
 'suph2012',
 'suph2017',
 'suph2022',
 'bacf1992',
 'bacf2002',
 'bacf2012',
 'bacf2017',
 'bacf2022',
 'supf1992',
 'supf2002',
 'supf2012',
 'supf2017',
 'supf2022']

info : les codes communes de df_50 commencent par un 0 et non un 1

In [14]:
df_final = df_filtered[colbis]

In [15]:
df_final.columns = 'DIP_' + df_final.columns

In [16]:
df_final.shape

(33803, 20)

In [17]:
df_final = pd.concat([df_filtered[['dep', 'nomdep', 'codecommune', 'nomcommune']], df_final], axis = 1)

In [18]:
df_final['DBL_bug'] = 0
df_final.shape

(33803, 25)

In [19]:
df_final.head(2)

,dep,nomdep,codecommune,nomcommune,DIP_bach1992,DIP_bach2002,DIP_bach2012,DIP_bach2017,DIP_bach2022,DIP_suph1992,...,DIP_bacf2002,DIP_bacf2012,DIP_bacf2017,DIP_bacf2022,DIP_supf1992,DIP_supf2002,DIP_supf2012,DIP_supf2017,DIP_supf2022,DBL_bug
0,1,AIN,01001,ABERGEMENT-CLEMENCIAT,9.0,29.0,42.0,52,62,14.0,...,26.0,42.0,52,62,11.0,29.0,71.0,64,57,0
1,1,AIN,01002,ABERGEMENT-DE-VAREY,10.0,7.0,19.0,33,47,10.0,...,11.0,5.0,30,55,2.0,8.0,44.0,26,8,0

In [20]:
new_row = ['*', '*', 'code', '*'] + [np.nan] * 20+[1]
len (new_row)

25

In [21]:
for i,code in enumerate(absent) :
    new_row = ['*', '*', code, '*'] + [np.nan] * 20 + [1]
    row_df = pd.DataFrame([new_row], columns=df_final.columns)
    df_final = pd.concat([df_final, row_df], ignore_index=True)
df_final.shape

(33830, 25)

## <a name="Import"></a>Partie 3 : Export CSV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#TOP">&uarr;</a>

In [22]:
df_final.to_csv('../DATA/EXPORT_CSV/final_DIP_diplomescommunes.csv', sep=';', index=False)

: